[package]
name = "decrypt"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
once_cell = "1.9.0"
rayon = "1.5.1"
serde = { version = "1.0.132", features = ["derive"] }
structopt = "0.3.25"
